CIRCUITPY_WIFI_SSID = "iot-wlan-2024"
CIRCUITPY_WIFI_PASSWORD = "mci_lecture&42"

MQTT_BROKER = "158.180.44.179"
MQTT_PORT = 1883
MQTT_USER = "bobm"
MQTT_PASSWORD = "letmein"
MQTT_CLIENT_ID= "pico_w_client"
MQTT_BASE_TOPIC = "iiot/group/test/sensor"
READING_INTERVAL_SECONDS = 30