services:
  influxdb:
    image: influxdb:2.7
    healthcheck:
      test: ["CMD-SHELL", "curl -f -H 'Authorization: Bearer ${INFLUXDB_TOKEN}' http://localhost:8086/health || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_BUCKET_RETENTION: ${INFLUXDB_RETENTION}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    environment:
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      influxdb:
        condition: service_healthy
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      INFLUXDB_HOST: ${INFLUXDB_HOST}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      TELEGRAF_SERVERS: ${TELEGRAF_SERVERS}
      TELEGRAF_CLIENT_ID: ${TELEGRAF_CLIENT_ID}
      TELEGRAF_USERNAME: ${TELEGRAF_USERNAME}
      TELEGRAF_PASSWORD: ${TELEGRAF_PASSWORD}
      TELEGRAF_COLLECTION_INTERVAL: ${TELEGRAF_COLLECTION_INTERVAL}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

volumes:
  influxdb_data:
  grafana_data:
